### PR TITLE
Update input.css

### PR DESCRIPTION
**Pull request by shayrapetyan**
This code set style(color:red) for *

### CODE REVIEW

**Comment by rotarytheme** [comment]
We don't change external files from plugins as this gets overridden with subsequent updates. Although it may look like this is part of our theme or plugin, it is part of advanced custom fields.

Pull request will not be merged.

**Comment by HyperGlide** [comment]
okay. Thank. Is there a way to kill or close the branch.

Cheers.

**Comment by rotarytheme** [comment]
I don't know but you can override any CSS in the custom CSS area

**Comment by HyperGlide** [comment]
When I look at this commit, I think it is not needed. 

Suggest it is just killed.

**Pull request closed without merging**
